/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

import UI_side_ads from "./UI_side_ads";
import UI_hot_game from "./UI_hot_game";
import UI_NativeInPage from "./UI_NativeInPage";
import UI_AdInpageComp from "./UI_AdInpageComp";
import UI_iconLongComp from "./UI_iconLongComp";
import UI_OpenAds from "./UI_OpenAds";
import UI_view_endshare from "./UI_view_endshare";
import UI_CommonEndReward from "./UI_CommonEndReward";
import UI_view_game_icon from "./UI_view_game_icon";
import UI_view_end_games from "./UI_view_end_games";
import UI_view_title from "./UI_view_title";
import UI_CommonOffline from "./UI_CommonOffline";
import UI_CommonTrySkin from "./UI_CommonTrySkin";
import UI_view_item_try_skin from "./UI_view_item_try_skin";
import UI_CommonSet from "./UI_CommonSet";
import UI_btn_toggle_01 from "./UI_btn_toggle_01";
import UI_view_set from "./UI_view_set";
import UI_CommonRoll from "./UI_CommonRoll";
import UI_view_item_roll from "./UI_view_item_roll";
import UI_view_roll_bg from "./UI_view_roll_bg";
import UI_CommonEndShare from "./UI_CommonEndShare";
import UI_CommonGameEgg from "./UI_CommonGameEgg";
import UI_info from "./UI_info";
import UI_btn_getegg from "./UI_btn_getegg";
import UI_eggItem from "./UI_eggItem";
import UI_eggIcon from "./UI_eggIcon";
import UI_SideGames from "./UI_SideGames";
import UI_CommonOneMore from "./UI_CommonOneMore";
import UI_view_one_more from "./UI_view_one_more";
import UI_btn_toggle_02 from "./UI_btn_toggle_02";
import UI_FlyPanel from "./UI_FlyPanel";
import UI_view_fly_coin from "./UI_view_fly_coin";
import UI_NativeIcon from "./UI_NativeIcon";
import UI_CommonLockScreen from "./UI_CommonLockScreen";
import UI_End3X3Ad from "./UI_End3X3Ad";
import UI_CommonSign from "./UI_CommonSign";
import UI_btn_double_get from "./UI_btn_double_get";
import UI_view_item_sign from "./UI_view_item_sign";
import UI_view_common_sign from "./UI_view_common_sign";
import UI_CommonEndSliderADs from "./UI_CommonEndSliderADs";
import UI_Native320 from "./UI_Native320";
import UI_CommonSign2 from "./UI_CommonSign2";
import UI_btn_normal0 from "./UI_btn_normal0";
import UI_SignItem from "./UI_SignItem";
import UI_ExSkin from "./UI_ExSkin";
import UI_btn_twoIcon from "./UI_btn_twoIcon";
import UI_tog_progress from "./UI_tog_progress";
import UI_BonusBox from "./UI_BonusBox";
import UI_btn_watch from "./UI_btn_watch";
import UI_TrySkin from "./UI_TrySkin";
import UI_toggle_nogame from "./UI_toggle_nogame";
import UI_NativeInterstitial from "./UI_NativeInterstitial";
import UI_NativeBigAd from "./UI_NativeBigAd";
import UI_btn_normal from "./UI_btn_normal";
import UI_btn_native from "./UI_btn_native";
import UI_CommonLoad from "./UI_CommonLoad";
import UI_view_load from "./UI_view_load";
import UI_btn_ad from "./UI_btn_ad";
import UI_NativeInterstitial_01 from "./UI_NativeInterstitial_01";
import UI_NativeInterAd from "./UI_NativeInterAd";
import UI_NativeIconLong from "./UI_NativeIconLong";
import UI_OppoEndExGame from "./UI_OppoEndExGame";
import UI_FakeBanner_V from "./UI_FakeBanner_V";
import UI_CommonToast from "./UI_CommonToast";
import UI_view_toast from "./UI_view_toast";
import UI_FakeRewardVideo from "./UI_FakeRewardVideo";
import UI_FakeInterstital from "./UI_FakeInterstital";
import UI_EndSlideGames from "./UI_EndSlideGames";
import UI_slideAds from "./UI_slideAds";
import UI_view_item_game from "./UI_view_item_game";
import UI_view_item_game140 from "./UI_view_item_game140";
import UI_BonusItem from "./UI_BonusItem";
import UI_tog_key from "./UI_tog_key";
import UI_view_item_sign_big from "./UI_view_item_sign_big";
import UI_ImageBanner from "./UI_ImageBanner";
import UI_SelfBanner from "./UI_SelfBanner";
import UI_GameCenter from "./UI_GameCenter";
import UI_item_game from "./UI_item_game";
import UI_item_gameBig from "./UI_item_gameBig";
import UI_GameIconF from "./UI_GameIconF";
import UI_WxSideGames from "./UI_WxSideGames";
import UI_item_gameSmall from "./UI_item_gameSmall";
import UI_CommonSign_02 from "./UI_CommonSign_02";
import UI_view_item_sign_02 from "./UI_view_item_sign_02";
import UI_CommonEndLose from "./UI_CommonEndLose";
import UI_CommonUnlockProgress from "./UI_CommonUnlockProgress";
import UI_sliderADs from "./UI_sliderADs";
import UI_rewardPannel from "./UI_rewardPannel";
import UI_view_sharegames_big from "./UI_view_sharegames_big";

export default class LTGameBinder{
	public static bindAll():void {
		fgui.UIObjectFactory.setExtension(UI_side_ads.URL, UI_side_ads);
		fgui.UIObjectFactory.setExtension(UI_hot_game.URL, UI_hot_game);
		fgui.UIObjectFactory.setExtension(UI_NativeInPage.URL, UI_NativeInPage);
		fgui.UIObjectFactory.setExtension(UI_AdInpageComp.URL, UI_AdInpageComp);
		fgui.UIObjectFactory.setExtension(UI_iconLongComp.URL, UI_iconLongComp);
		fgui.UIObjectFactory.setExtension(UI_OpenAds.URL, UI_OpenAds);
		fgui.UIObjectFactory.setExtension(UI_view_endshare.URL, UI_view_endshare);
		fgui.UIObjectFactory.setExtension(UI_CommonEndReward.URL, UI_CommonEndReward);
		fgui.UIObjectFactory.setExtension(UI_view_game_icon.URL, UI_view_game_icon);
		fgui.UIObjectFactory.setExtension(UI_view_end_games.URL, UI_view_end_games);
		fgui.UIObjectFactory.setExtension(UI_view_title.URL, UI_view_title);
		fgui.UIObjectFactory.setExtension(UI_CommonOffline.URL, UI_CommonOffline);
		fgui.UIObjectFactory.setExtension(UI_CommonTrySkin.URL, UI_CommonTrySkin);
		fgui.UIObjectFactory.setExtension(UI_view_item_try_skin.URL, UI_view_item_try_skin);
		fgui.UIObjectFactory.setExtension(UI_CommonSet.URL, UI_CommonSet);
		fgui.UIObjectFactory.setExtension(UI_btn_toggle_01.URL, UI_btn_toggle_01);
		fgui.UIObjectFactory.setExtension(UI_view_set.URL, UI_view_set);
		fgui.UIObjectFactory.setExtension(UI_CommonRoll.URL, UI_CommonRoll);
		fgui.UIObjectFactory.setExtension(UI_view_item_roll.URL, UI_view_item_roll);
		fgui.UIObjectFactory.setExtension(UI_view_roll_bg.URL, UI_view_roll_bg);
		fgui.UIObjectFactory.setExtension(UI_CommonEndShare.URL, UI_CommonEndShare);
		fgui.UIObjectFactory.setExtension(UI_CommonGameEgg.URL, UI_CommonGameEgg);
		fgui.UIObjectFactory.setExtension(UI_info.URL, UI_info);
		fgui.UIObjectFactory.setExtension(UI_btn_getegg.URL, UI_btn_getegg);
		fgui.UIObjectFactory.setExtension(UI_eggItem.URL, UI_eggItem);
		fgui.UIObjectFactory.setExtension(UI_eggIcon.URL, UI_eggIcon);
		fgui.UIObjectFactory.setExtension(UI_SideGames.URL, UI_SideGames);
		fgui.UIObjectFactory.setExtension(UI_CommonOneMore.URL, UI_CommonOneMore);
		fgui.UIObjectFactory.setExtension(UI_view_one_more.URL, UI_view_one_more);
		fgui.UIObjectFactory.setExtension(UI_btn_toggle_02.URL, UI_btn_toggle_02);
		fgui.UIObjectFactory.setExtension(UI_FlyPanel.URL, UI_FlyPanel);
		fgui.UIObjectFactory.setExtension(UI_view_fly_coin.URL, UI_view_fly_coin);
		fgui.UIObjectFactory.setExtension(UI_NativeIcon.URL, UI_NativeIcon);
		fgui.UIObjectFactory.setExtension(UI_CommonLockScreen.URL, UI_CommonLockScreen);
		fgui.UIObjectFactory.setExtension(UI_End3X3Ad.URL, UI_End3X3Ad);
		fgui.UIObjectFactory.setExtension(UI_CommonSign.URL, UI_CommonSign);
		fgui.UIObjectFactory.setExtension(UI_btn_double_get.URL, UI_btn_double_get);
		fgui.UIObjectFactory.setExtension(UI_view_item_sign.URL, UI_view_item_sign);
		fgui.UIObjectFactory.setExtension(UI_view_common_sign.URL, UI_view_common_sign);
		fgui.UIObjectFactory.setExtension(UI_CommonEndSliderADs.URL, UI_CommonEndSliderADs);
		fgui.UIObjectFactory.setExtension(UI_Native320.URL, UI_Native320);
		fgui.UIObjectFactory.setExtension(UI_CommonSign2.URL, UI_CommonSign2);
		fgui.UIObjectFactory.setExtension(UI_btn_normal0.URL, UI_btn_normal0);
		fgui.UIObjectFactory.setExtension(UI_SignItem.URL, UI_SignItem);
		fgui.UIObjectFactory.setExtension(UI_ExSkin.URL, UI_ExSkin);
		fgui.UIObjectFactory.setExtension(UI_btn_twoIcon.URL, UI_btn_twoIcon);
		fgui.UIObjectFactory.setExtension(UI_tog_progress.URL, UI_tog_progress);
		fgui.UIObjectFactory.setExtension(UI_BonusBox.URL, UI_BonusBox);
		fgui.UIObjectFactory.setExtension(UI_btn_watch.URL, UI_btn_watch);
		fgui.UIObjectFactory.setExtension(UI_TrySkin.URL, UI_TrySkin);
		fgui.UIObjectFactory.setExtension(UI_toggle_nogame.URL, UI_toggle_nogame);
		fgui.UIObjectFactory.setExtension(UI_NativeInterstitial.URL, UI_NativeInterstitial);
		fgui.UIObjectFactory.setExtension(UI_NativeBigAd.URL, UI_NativeBigAd);
		fgui.UIObjectFactory.setExtension(UI_btn_normal.URL, UI_btn_normal);
		fgui.UIObjectFactory.setExtension(UI_btn_native.URL, UI_btn_native);
		fgui.UIObjectFactory.setExtension(UI_CommonLoad.URL, UI_CommonLoad);
		fgui.UIObjectFactory.setExtension(UI_view_load.URL, UI_view_load);
		fgui.UIObjectFactory.setExtension(UI_btn_ad.URL, UI_btn_ad);
		fgui.UIObjectFactory.setExtension(UI_NativeInterstitial_01.URL, UI_NativeInterstitial_01);
		fgui.UIObjectFactory.setExtension(UI_NativeInterAd.URL, UI_NativeInterAd);
		fgui.UIObjectFactory.setExtension(UI_NativeIconLong.URL, UI_NativeIconLong);
		fgui.UIObjectFactory.setExtension(UI_OppoEndExGame.URL, UI_OppoEndExGame);
		fgui.UIObjectFactory.setExtension(UI_FakeBanner_V.URL, UI_FakeBanner_V);
		fgui.UIObjectFactory.setExtension(UI_CommonToast.URL, UI_CommonToast);
		fgui.UIObjectFactory.setExtension(UI_view_toast.URL, UI_view_toast);
		fgui.UIObjectFactory.setExtension(UI_FakeRewardVideo.URL, UI_FakeRewardVideo);
		fgui.UIObjectFactory.setExtension(UI_FakeInterstital.URL, UI_FakeInterstital);
		fgui.UIObjectFactory.setExtension(UI_EndSlideGames.URL, UI_EndSlideGames);
		fgui.UIObjectFactory.setExtension(UI_slideAds.URL, UI_slideAds);
		fgui.UIObjectFactory.setExtension(UI_view_item_game.URL, UI_view_item_game);
		fgui.UIObjectFactory.setExtension(UI_view_item_game140.URL, UI_view_item_game140);
		fgui.UIObjectFactory.setExtension(UI_BonusItem.URL, UI_BonusItem);
		fgui.UIObjectFactory.setExtension(UI_tog_key.URL, UI_tog_key);
		fgui.UIObjectFactory.setExtension(UI_view_item_sign_big.URL, UI_view_item_sign_big);
		fgui.UIObjectFactory.setExtension(UI_ImageBanner.URL, UI_ImageBanner);
		fgui.UIObjectFactory.setExtension(UI_SelfBanner.URL, UI_SelfBanner);
		fgui.UIObjectFactory.setExtension(UI_GameCenter.URL, UI_GameCenter);
		fgui.UIObjectFactory.setExtension(UI_item_game.URL, UI_item_game);
		fgui.UIObjectFactory.setExtension(UI_item_gameBig.URL, UI_item_gameBig);
		fgui.UIObjectFactory.setExtension(UI_GameIconF.URL, UI_GameIconF);
		fgui.UIObjectFactory.setExtension(UI_WxSideGames.URL, UI_WxSideGames);
		fgui.UIObjectFactory.setExtension(UI_item_gameSmall.URL, UI_item_gameSmall);
		fgui.UIObjectFactory.setExtension(UI_CommonSign_02.URL, UI_CommonSign_02);
		fgui.UIObjectFactory.setExtension(UI_view_item_sign_02.URL, UI_view_item_sign_02);
		fgui.UIObjectFactory.setExtension(UI_CommonEndLose.URL, UI_CommonEndLose);
		fgui.UIObjectFactory.setExtension(UI_CommonUnlockProgress.URL, UI_CommonUnlockProgress);
		fgui.UIObjectFactory.setExtension(UI_sliderADs.URL, UI_sliderADs);
		fgui.UIObjectFactory.setExtension(UI_rewardPannel.URL, UI_rewardPannel);
		fgui.UIObjectFactory.setExtension(UI_view_sharegames_big.URL, UI_view_sharegames_big);
	}
}