/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

import UI_side_ads from "./UI_side_ads";
import UI_hot_game from "./UI_hot_game";
import UI_view_endshare from "./UI_view_endshare";
import UI_CommonEndReward from "./UI_CommonEndReward";
import UI_view_game_icon from "./UI_view_game_icon";
import UI_view_end_games from "./UI_view_end_games";
import UI_view_title from "./UI_view_title";
import UI_CommonOffline from "./UI_CommonOffline";
import UI_CommonTrySkin from "./UI_CommonTrySkin";
import UI_view_item_try_skin from "./UI_view_item_try_skin";
import UI_CommonSet from "./UI_CommonSet";
import UI_btn_toggle_01 from "./UI_btn_toggle_01";
import UI_view_set from "./UI_view_set";
import UI_CommonRoll from "./UI_CommonRoll";
import UI_view_item_roll from "./UI_view_item_roll";
import UI_view_roll_bg from "./UI_view_roll_bg";
import UI_CommonEndShare from "./UI_CommonEndShare";
import UI_SideGames from "./UI_SideGames";
import UI_CommonOneMore from "./UI_CommonOneMore";
import UI_view_one_more from "./UI_view_one_more";
import UI_btn_toggle_02 from "./UI_btn_toggle_02";
import UI_FlyPanel from "./UI_FlyPanel";
import UI_view_fly_coin from "./UI_view_fly_coin";
import UI_NativeIcon from "./UI_NativeIcon";
import UI_CommonLockScreen from "./UI_CommonLockScreen";
import UI_CommonSign from "./UI_CommonSign";
import UI_btn_double_get from "./UI_btn_double_get";
import UI_view_item_sign from "./UI_view_item_sign";
import UI_view_common_sign from "./UI_view_common_sign";
import UI_CommonEndSliderADs from "./UI_CommonEndSliderADs";
import UI_Native320 from "./UI_Native320";
import UI_NativeInterstitial from "./UI_NativeInterstitial";
import UI_NativeBigAd from "./UI_NativeBigAd";
import UI_btn_normal from "./UI_btn_normal";
import UI_btn_native from "./UI_btn_native";
import UI_CommonLoad from "./UI_CommonLoad";
import UI_view_load from "./UI_view_load";
import UI_NativeInpage from "./UI_NativeInpage";
import UI_FakeBanner_V from "./UI_FakeBanner_V";
import UI_CommonToast from "./UI_CommonToast";
import UI_view_toast from "./UI_view_toast";
import UI_FakeRewardVideo from "./UI_FakeRewardVideo";
import UI_FakeInterstital from "./UI_FakeInterstital";
import UI_EndSlideGames from "./UI_EndSlideGames";
import UI_slideAds from "./UI_slideAds";
import UI_view_item_game from "./UI_view_item_game";
import UI_view_item_game140 from "./UI_view_item_game140";
import UI_view_item_sign_big from "./UI_view_item_sign_big";
import UI_ImageBanner from "./UI_ImageBanner";
import UI_CommonSign_02 from "./UI_CommonSign_02";
import UI_view_item_sign_02 from "./UI_view_item_sign_02";
import UI_CommonEndLose from "./UI_CommonEndLose";
import UI_CommonUnlockProgress from "./UI_CommonUnlockProgress";
import UI_sliderADs from "./UI_sliderADs";
import UI_view_sharegames_big from "./UI_view_sharegames_big";

export default class LTGameBinder {
	public static bindAll():void {
		fgui.UIObjectFactory.setExtension(UI_side_ads.URL, UI_side_ads);
		fgui.UIObjectFactory.setExtension(UI_hot_game.URL, UI_hot_game);
		fgui.UIObjectFactory.setExtension(UI_view_endshare.URL, UI_view_endshare);
		fgui.UIObjectFactory.setExtension(UI_CommonEndReward.URL, UI_CommonEndReward);
		fgui.UIObjectFactory.setExtension(UI_view_game_icon.URL, UI_view_game_icon);
		fgui.UIObjectFactory.setExtension(UI_view_end_games.URL, UI_view_end_games);
		fgui.UIObjectFactory.setExtension(UI_view_title.URL, UI_view_title);
		fgui.UIObjectFactory.setExtension(UI_CommonOffline.URL, UI_CommonOffline);
		fgui.UIObjectFactory.setExtension(UI_CommonTrySkin.URL, UI_CommonTrySkin);
		fgui.UIObjectFactory.setExtension(UI_view_item_try_skin.URL, UI_view_item_try_skin);
		fgui.UIObjectFactory.setExtension(UI_CommonSet.URL, UI_CommonSet);
		fgui.UIObjectFactory.setExtension(UI_btn_toggle_01.URL, UI_btn_toggle_01);
		fgui.UIObjectFactory.setExtension(UI_view_set.URL, UI_view_set);
		fgui.UIObjectFactory.setExtension(UI_CommonRoll.URL, UI_CommonRoll);
		fgui.UIObjectFactory.setExtension(UI_view_item_roll.URL, UI_view_item_roll);
		fgui.UIObjectFactory.setExtension(UI_view_roll_bg.URL, UI_view_roll_bg);
		fgui.UIObjectFactory.setExtension(UI_CommonEndShare.URL, UI_CommonEndShare);
		fgui.UIObjectFactory.setExtension(UI_SideGames.URL, UI_SideGames);
		fgui.UIObjectFactory.setExtension(UI_CommonOneMore.URL, UI_CommonOneMore);
		fgui.UIObjectFactory.setExtension(UI_view_one_more.URL, UI_view_one_more);
		fgui.UIObjectFactory.setExtension(UI_btn_toggle_02.URL, UI_btn_toggle_02);
		fgui.UIObjectFactory.setExtension(UI_FlyPanel.URL, UI_FlyPanel);
		fgui.UIObjectFactory.setExtension(UI_view_fly_coin.URL, UI_view_fly_coin);
		fgui.UIObjectFactory.setExtension(UI_NativeIcon.URL, UI_NativeIcon);
		fgui.UIObjectFactory.setExtension(UI_CommonLockScreen.URL, UI_CommonLockScreen);
		fgui.UIObjectFactory.setExtension(UI_CommonSign.URL, UI_CommonSign);
		fgui.UIObjectFactory.setExtension(UI_btn_double_get.URL, UI_btn_double_get);
		fgui.UIObjectFactory.setExtension(UI_view_item_sign.URL, UI_view_item_sign);
		fgui.UIObjectFactory.setExtension(UI_view_common_sign.URL, UI_view_common_sign);
		fgui.UIObjectFactory.setExtension(UI_CommonEndSliderADs.URL, UI_CommonEndSliderADs);
		fgui.UIObjectFactory.setExtension(UI_Native320.URL, UI_Native320);
		fgui.UIObjectFactory.setExtension(UI_NativeInterstitial.URL, UI_NativeInterstitial);
		fgui.UIObjectFactory.setExtension(UI_NativeBigAd.URL, UI_NativeBigAd);
		fgui.UIObjectFactory.setExtension(UI_btn_normal.URL, UI_btn_normal);
		fgui.UIObjectFactory.setExtension(UI_btn_native.URL, UI_btn_native);
		fgui.UIObjectFactory.setExtension(UI_CommonLoad.URL, UI_CommonLoad);
		fgui.UIObjectFactory.setExtension(UI_view_load.URL, UI_view_load);
		fgui.UIObjectFactory.setExtension(UI_NativeInpage.URL, UI_NativeInpage);
		fgui.UIObjectFactory.setExtension(UI_FakeBanner_V.URL, UI_FakeBanner_V);
		fgui.UIObjectFactory.setExtension(UI_CommonToast.URL, UI_CommonToast);
		fgui.UIObjectFactory.setExtension(UI_view_toast.URL, UI_view_toast);
		fgui.UIObjectFactory.setExtension(UI_FakeRewardVideo.URL, UI_FakeRewardVideo);
		fgui.UIObjectFactory.setExtension(UI_FakeInterstital.URL, UI_FakeInterstital);
		fgui.UIObjectFactory.setExtension(UI_EndSlideGames.URL, UI_EndSlideGames);
		fgui.UIObjectFactory.setExtension(UI_slideAds.URL, UI_slideAds);
		fgui.UIObjectFactory.setExtension(UI_view_item_game.URL, UI_view_item_game);
		fgui.UIObjectFactory.setExtension(UI_view_item_game140.URL, UI_view_item_game140);
		fgui.UIObjectFactory.setExtension(UI_view_item_sign_big.URL, UI_view_item_sign_big);
		fgui.UIObjectFactory.setExtension(UI_ImageBanner.URL, UI_ImageBanner);
		fgui.UIObjectFactory.setExtension(UI_CommonSign_02.URL, UI_CommonSign_02);
		fgui.UIObjectFactory.setExtension(UI_view_item_sign_02.URL, UI_view_item_sign_02);
		fgui.UIObjectFactory.setExtension(UI_CommonEndLose.URL, UI_CommonEndLose);
		fgui.UIObjectFactory.setExtension(UI_CommonUnlockProgress.URL, UI_CommonUnlockProgress);
		fgui.UIObjectFactory.setExtension(UI_sliderADs.URL, UI_sliderADs);
		fgui.UIObjectFactory.setExtension(UI_view_sharegames_big.URL, UI_view_sharegames_big);
	}
}