/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

import UI_side_ads from "./UI_side_ads";
import UI_hot_game from "./UI_hot_game";
import UI_NativeInPage from "./UI_NativeInPage";
import UI_AdInpageComp from "./UI_AdInpageComp";
import UI_iconLongComp from "./UI_iconLongComp";
import UI_OpenAds from "./UI_OpenAds";
import UI_view_game_icon1 from "./UI_view_game_icon1";
import UI_view_end_games from "./UI_view_end_games";
import UI_view_game_icon from "./UI_view_game_icon";
import UI_view_item_game164 from "./UI_view_item_game164";
import UI_SideGames from "./UI_SideGames";
import UI_Channel from "./UI_Channel";
import UI_FlyPanel from "./UI_FlyPanel";
import UI_view_fly_coin from "./UI_view_fly_coin";
import UI_NativeIcon from "./UI_NativeIcon";
import UI_CommonLockScreen from "./UI_CommonLockScreen";
import UI_End3X3Ad from "./UI_End3X3Ad";
import UI_CommonEndSliderADs from "./UI_CommonEndSliderADs";
import UI_btn_normal from "./UI_btn_normal";
import UI_CommonLoad from "./UI_CommonLoad";
import UI_view_load from "./UI_view_load";
import UI_NativeIconLong from "./UI_NativeIconLong";
import UI_FakeBanner_V from "./UI_FakeBanner_V";
import UI_CommonToast from "./UI_CommonToast";
import UI_view_toast from "./UI_view_toast";
import UI_FakeRewardVideo from "./UI_FakeRewardVideo";
import UI_FakeInterstital from "./UI_FakeInterstital";
import UI_EndSlideGames from "./UI_EndSlideGames";
import UI_slideAds from "./UI_slideAds";
import UI_view_item_game from "./UI_view_item_game";
import UI_view_item_game140 from "./UI_view_item_game140";
import UI_ImageBanner from "./UI_ImageBanner";
import UI_SelfBanner from "./UI_SelfBanner";
import UI_GameCenter from "./UI_GameCenter";
import UI_item_game from "./UI_item_game";
import UI_item_gameBig from "./UI_item_gameBig";
import UI_GameIconF from "./UI_GameIconF";
import UI_WxSideGames from "./UI_WxSideGames";
import UI_item_gameSmall from "./UI_item_gameSmall";
import UI_GameCenterBig from "./UI_GameCenterBig";
import UI_item_gameMax from "./UI_item_gameMax";
import UI_bottomGames from "./UI_bottomGames";
import UI_view_item_game128 from "./UI_view_item_game128";
import UI_sliderADs from "./UI_sliderADs";
import UI_OppoEnd from "./UI_OppoEnd";
import UI_btn_scaler_yellow from "./UI_btn_scaler_yellow";
import UI_normal_ad_btn from "./UI_normal_ad_btn";
import UI_btn_red_scale from "./UI_btn_red_scale";
import UI_view_sharegames_big from "./UI_view_sharegames_big";

export default class LTGameBinder{
	public static bindAll():void {
		fgui.UIObjectFactory.setExtension(UI_side_ads.URL, UI_side_ads);
		fgui.UIObjectFactory.setExtension(UI_hot_game.URL, UI_hot_game);
		fgui.UIObjectFactory.setExtension(UI_NativeInPage.URL, UI_NativeInPage);
		fgui.UIObjectFactory.setExtension(UI_AdInpageComp.URL, UI_AdInpageComp);
		fgui.UIObjectFactory.setExtension(UI_iconLongComp.URL, UI_iconLongComp);
		fgui.UIObjectFactory.setExtension(UI_OpenAds.URL, UI_OpenAds);
		fgui.UIObjectFactory.setExtension(UI_view_game_icon1.URL, UI_view_game_icon1);
		fgui.UIObjectFactory.setExtension(UI_view_end_games.URL, UI_view_end_games);
		fgui.UIObjectFactory.setExtension(UI_view_game_icon.URL, UI_view_game_icon);
		fgui.UIObjectFactory.setExtension(UI_view_item_game164.URL, UI_view_item_game164);
		fgui.UIObjectFactory.setExtension(UI_SideGames.URL, UI_SideGames);
		fgui.UIObjectFactory.setExtension(UI_Channel.URL, UI_Channel);
		fgui.UIObjectFactory.setExtension(UI_FlyPanel.URL, UI_FlyPanel);
		fgui.UIObjectFactory.setExtension(UI_view_fly_coin.URL, UI_view_fly_coin);
		fgui.UIObjectFactory.setExtension(UI_NativeIcon.URL, UI_NativeIcon);
		fgui.UIObjectFactory.setExtension(UI_CommonLockScreen.URL, UI_CommonLockScreen);
		fgui.UIObjectFactory.setExtension(UI_End3X3Ad.URL, UI_End3X3Ad);
		fgui.UIObjectFactory.setExtension(UI_CommonEndSliderADs.URL, UI_CommonEndSliderADs);
		fgui.UIObjectFactory.setExtension(UI_btn_normal.URL, UI_btn_normal);
		fgui.UIObjectFactory.setExtension(UI_CommonLoad.URL, UI_CommonLoad);
		fgui.UIObjectFactory.setExtension(UI_view_load.URL, UI_view_load);
		fgui.UIObjectFactory.setExtension(UI_NativeIconLong.URL, UI_NativeIconLong);
		fgui.UIObjectFactory.setExtension(UI_FakeBanner_V.URL, UI_FakeBanner_V);
		fgui.UIObjectFactory.setExtension(UI_CommonToast.URL, UI_CommonToast);
		fgui.UIObjectFactory.setExtension(UI_view_toast.URL, UI_view_toast);
		fgui.UIObjectFactory.setExtension(UI_FakeRewardVideo.URL, UI_FakeRewardVideo);
		fgui.UIObjectFactory.setExtension(UI_FakeInterstital.URL, UI_FakeInterstital);
		fgui.UIObjectFactory.setExtension(UI_EndSlideGames.URL, UI_EndSlideGames);
		fgui.UIObjectFactory.setExtension(UI_slideAds.URL, UI_slideAds);
		fgui.UIObjectFactory.setExtension(UI_view_item_game.URL, UI_view_item_game);
		fgui.UIObjectFactory.setExtension(UI_view_item_game140.URL, UI_view_item_game140);
		fgui.UIObjectFactory.setExtension(UI_ImageBanner.URL, UI_ImageBanner);
		fgui.UIObjectFactory.setExtension(UI_SelfBanner.URL, UI_SelfBanner);
		fgui.UIObjectFactory.setExtension(UI_GameCenter.URL, UI_GameCenter);
		fgui.UIObjectFactory.setExtension(UI_item_game.URL, UI_item_game);
		fgui.UIObjectFactory.setExtension(UI_item_gameBig.URL, UI_item_gameBig);
		fgui.UIObjectFactory.setExtension(UI_GameIconF.URL, UI_GameIconF);
		fgui.UIObjectFactory.setExtension(UI_WxSideGames.URL, UI_WxSideGames);
		fgui.UIObjectFactory.setExtension(UI_item_gameSmall.URL, UI_item_gameSmall);
		fgui.UIObjectFactory.setExtension(UI_GameCenterBig.URL, UI_GameCenterBig);
		fgui.UIObjectFactory.setExtension(UI_item_gameMax.URL, UI_item_gameMax);
		fgui.UIObjectFactory.setExtension(UI_bottomGames.URL, UI_bottomGames);
		fgui.UIObjectFactory.setExtension(UI_view_item_game128.URL, UI_view_item_game128);
		fgui.UIObjectFactory.setExtension(UI_sliderADs.URL, UI_sliderADs);
		fgui.UIObjectFactory.setExtension(UI_OppoEnd.URL, UI_OppoEnd);
		fgui.UIObjectFactory.setExtension(UI_btn_scaler_yellow.URL, UI_btn_scaler_yellow);
		fgui.UIObjectFactory.setExtension(UI_normal_ad_btn.URL, UI_normal_ad_btn);
		fgui.UIObjectFactory.setExtension(UI_btn_red_scale.URL, UI_btn_red_scale);
		fgui.UIObjectFactory.setExtension(UI_view_sharegames_big.URL, UI_view_sharegames_big);
	}
}