/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

import LTG_UI_Set from "./LTG_UI_Set";
import LTG_UI_Notice from "./LTG_UI_Notice";
import LTG_UI_view_notice from "./LTG_UI_view_notice";
import LTG_UI_AddShortcut from "./LTG_UI_AddShortcut";
import LTG_UI_Roll from "./LTG_UI_Roll";
import LTG_UI_btn_watchad_roll from "./LTG_UI_btn_watchad_roll";
import LTG_UI_item_view_roll from "./LTG_UI_item_view_roll";
import LTG_UI_view_roll_panel from "./LTG_UI_view_roll_panel";
import LTG_UI_view_roll from "./LTG_UI_view_roll";
import LTG_UI_WatchDY from "./LTG_UI_WatchDY";
import LTG_UI_view_watchdy from "./LTG_UI_view_watchdy";
import LTG_UI_Sign from "./LTG_UI_Sign";
import LTG_UI_view_sign from "./LTG_UI_view_sign";
import LTG_UI_view_item_sign_01 from "./LTG_UI_view_item_sign_01";
import LTG_UI_btn_normalg from "./LTG_UI_btn_normalg";
import LTG_UI_view_title_set from "./LTG_UI_view_title_set";
import LTG_UI_HideMenu from "./LTG_UI_HideMenu";
import LTG_UI_view_hidemenu from "./LTG_UI_view_hidemenu";
import LTG_UI_toggle_01 from "./LTG_UI_toggle_01";
import LTG_UI_view_set from "./LTG_UI_view_set";
import LTG_UI_RewardCode from "./LTG_UI_RewardCode";
import LTG_UI_view_rewardcode from "./LTG_UI_view_rewardcode";
import LTG_UI_TrySkin from "./LTG_UI_TrySkin";
import LTG_UI_VideoList from "./LTG_UI_VideoList";
import LTG_UI_top3 from "./LTG_UI_top3";
import LTG_UI_iconVdieo from "./LTG_UI_iconVdieo";
import LTG_UI_videoItem from "./LTG_UI_videoItem";
import LTG_UI_normal_btn from "./LTG_UI_normal_btn";
import LTG_UI_RankList from "./LTG_UI_RankList";
import LTG_UI_view_item_sign_08 from "./LTG_UI_view_item_sign_08";
import LTG_UI_common_ad_btn from "./LTG_UI_common_ad_btn";
import LTG_UI_btn_morediamond from "./LTG_UI_btn_morediamond";
import LTG_UI_Win from "./LTG_UI_Win";
import LTG_UI_image_bar from "./LTG_UI_image_bar";
import LTG_UI_btn_unlock_ad_01 from "./LTG_UI_btn_unlock_ad_01";
import LTG_UI_view_unlock_progress from "./LTG_UI_view_unlock_progress";
import LTG_UI_EggUnlock from "./LTG_UI_EggUnlock";
import LTG_UI_view_enter_code from "./LTG_UI_view_enter_code";
import LTG_UI_UnlockItem from "./LTG_UI_UnlockItem";
import LTG_UI_btn_unlock_ad from "./LTG_UI_btn_unlock_ad";
import LTG_UI_btn_refuse from "./LTG_UI_btn_refuse";
import LTG_UI_view_unlock from "./LTG_UI_view_unlock";
import LTG_UI_ScreenShoot from "./LTG_UI_ScreenShoot";
import LTG_UI_EggWall from "./LTG_UI_EggWall";
import LTG_UI_view_item_egg1 from "./LTG_UI_view_item_egg1";
import LTG_UI_view_screenshoot_new from "./LTG_UI_view_screenshoot_new";
import LTG_UI_view_shortcut from "./LTG_UI_view_shortcut";
import LTG_UI_btn_next_2 from "./LTG_UI_btn_next_2";
import LTG_UI_btn_get from "./LTG_UI_btn_get";
import LTG_UI_try_view from "./LTG_UI_try_view";
import LTG_UI_EggDetail from "./LTG_UI_EggDetail";
import LTG_UI_Statement from "./LTG_UI_Statement";

export default class LTComBinder{
	public static bindAll():void {
		fgui.UIObjectFactory.setExtension(LTG_UI_Set.URL, LTG_UI_Set);
		fgui.UIObjectFactory.setExtension(LTG_UI_Notice.URL, LTG_UI_Notice);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_notice.URL, LTG_UI_view_notice);
		fgui.UIObjectFactory.setExtension(LTG_UI_AddShortcut.URL, LTG_UI_AddShortcut);
		fgui.UIObjectFactory.setExtension(LTG_UI_Roll.URL, LTG_UI_Roll);
		fgui.UIObjectFactory.setExtension(LTG_UI_btn_watchad_roll.URL, LTG_UI_btn_watchad_roll);
		fgui.UIObjectFactory.setExtension(LTG_UI_item_view_roll.URL, LTG_UI_item_view_roll);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_roll_panel.URL, LTG_UI_view_roll_panel);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_roll.URL, LTG_UI_view_roll);
		fgui.UIObjectFactory.setExtension(LTG_UI_WatchDY.URL, LTG_UI_WatchDY);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_watchdy.URL, LTG_UI_view_watchdy);
		fgui.UIObjectFactory.setExtension(LTG_UI_Sign.URL, LTG_UI_Sign);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_sign.URL, LTG_UI_view_sign);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_item_sign_01.URL, LTG_UI_view_item_sign_01);
		fgui.UIObjectFactory.setExtension(LTG_UI_btn_normalg.URL, LTG_UI_btn_normalg);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_title_set.URL, LTG_UI_view_title_set);
		fgui.UIObjectFactory.setExtension(LTG_UI_HideMenu.URL, LTG_UI_HideMenu);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_hidemenu.URL, LTG_UI_view_hidemenu);
		fgui.UIObjectFactory.setExtension(LTG_UI_toggle_01.URL, LTG_UI_toggle_01);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_set.URL, LTG_UI_view_set);
		fgui.UIObjectFactory.setExtension(LTG_UI_RewardCode.URL, LTG_UI_RewardCode);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_rewardcode.URL, LTG_UI_view_rewardcode);
		fgui.UIObjectFactory.setExtension(LTG_UI_TrySkin.URL, LTG_UI_TrySkin);
		fgui.UIObjectFactory.setExtension(LTG_UI_VideoList.URL, LTG_UI_VideoList);
		fgui.UIObjectFactory.setExtension(LTG_UI_top3.URL, LTG_UI_top3);
		fgui.UIObjectFactory.setExtension(LTG_UI_iconVdieo.URL, LTG_UI_iconVdieo);
		fgui.UIObjectFactory.setExtension(LTG_UI_videoItem.URL, LTG_UI_videoItem);
		fgui.UIObjectFactory.setExtension(LTG_UI_normal_btn.URL, LTG_UI_normal_btn);
		fgui.UIObjectFactory.setExtension(LTG_UI_RankList.URL, LTG_UI_RankList);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_item_sign_08.URL, LTG_UI_view_item_sign_08);
		fgui.UIObjectFactory.setExtension(LTG_UI_common_ad_btn.URL, LTG_UI_common_ad_btn);
		fgui.UIObjectFactory.setExtension(LTG_UI_btn_morediamond.URL, LTG_UI_btn_morediamond);
		fgui.UIObjectFactory.setExtension(LTG_UI_Win.URL, LTG_UI_Win);
		fgui.UIObjectFactory.setExtension(LTG_UI_image_bar.URL, LTG_UI_image_bar);
		fgui.UIObjectFactory.setExtension(LTG_UI_btn_unlock_ad_01.URL, LTG_UI_btn_unlock_ad_01);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_unlock_progress.URL, LTG_UI_view_unlock_progress);
		fgui.UIObjectFactory.setExtension(LTG_UI_EggUnlock.URL, LTG_UI_EggUnlock);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_enter_code.URL, LTG_UI_view_enter_code);
		fgui.UIObjectFactory.setExtension(LTG_UI_UnlockItem.URL, LTG_UI_UnlockItem);
		fgui.UIObjectFactory.setExtension(LTG_UI_btn_unlock_ad.URL, LTG_UI_btn_unlock_ad);
		fgui.UIObjectFactory.setExtension(LTG_UI_btn_refuse.URL, LTG_UI_btn_refuse);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_unlock.URL, LTG_UI_view_unlock);
		fgui.UIObjectFactory.setExtension(LTG_UI_ScreenShoot.URL, LTG_UI_ScreenShoot);
		fgui.UIObjectFactory.setExtension(LTG_UI_EggWall.URL, LTG_UI_EggWall);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_item_egg1.URL, LTG_UI_view_item_egg1);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_screenshoot_new.URL, LTG_UI_view_screenshoot_new);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_shortcut.URL, LTG_UI_view_shortcut);
		fgui.UIObjectFactory.setExtension(LTG_UI_btn_next_2.URL, LTG_UI_btn_next_2);
		fgui.UIObjectFactory.setExtension(LTG_UI_btn_get.URL, LTG_UI_btn_get);
		fgui.UIObjectFactory.setExtension(LTG_UI_try_view.URL, LTG_UI_try_view);
		fgui.UIObjectFactory.setExtension(LTG_UI_EggDetail.URL, LTG_UI_EggDetail);
		fgui.UIObjectFactory.setExtension(LTG_UI_Statement.URL, LTG_UI_Statement);
	}
}