/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

import LTG_UI_Set from "./LTG_UI_Set";
import LTG_UI_Notice from "./LTG_UI_Notice";
import LTG_UI_view_notice from "./LTG_UI_view_notice";
import LTG_UI_AddShortcut from "./LTG_UI_AddShortcut";
import LTG_UI_view_addshortcut from "./LTG_UI_view_addshortcut";
import LTG_UI_FindGame from "./LTG_UI_FindGame";
import LTG_UI_view_findgame from "./LTG_UI_view_findgame";
import LTG_UI_MyGame from "./LTG_UI_MyGame";
import LTG_UI_view_mygame from "./LTG_UI_view_mygame";
import LTG_UI_Zhuawawa from "./LTG_UI_Zhuawawa";
import LTG_UI_view_zhuazi from "./LTG_UI_view_zhuazi";
import LTG_UI_view_zww from "./LTG_UI_view_zww";
import LTG_UI_EggWall from "./LTG_UI_EggWall";
import LTG_UI_btn_show_tips from "./LTG_UI_btn_show_tips";
import LTG_UI_item_view_eggwall from "./LTG_UI_item_view_eggwall";
import LTG_UI_view_grow_01 from "./LTG_UI_view_grow_01";
import LTG_UI_Roll from "./LTG_UI_Roll";
import LTG_UI_item_view_roll from "./LTG_UI_item_view_roll";
import LTG_UI_view_roll_panel from "./LTG_UI_view_roll_panel";
import LTG_UI_view_roll from "./LTG_UI_view_roll";
import LTG_UI_WatchDY from "./LTG_UI_WatchDY";
import LTG_UI_view_watchdy from "./LTG_UI_view_watchdy";
import LTG_UI_Sign from "./LTG_UI_Sign";
import LTG_UI_view_sign from "./LTG_UI_view_sign";
import LTG_UI_view_item_sign_01 from "./LTG_UI_view_item_sign_01";
import LTG_UI_view_item_sign_02 from "./LTG_UI_view_item_sign_02";
import LTG_UI_view_item_sign_03 from "./LTG_UI_view_item_sign_03";
import LTG_UI_view_item_sign_05 from "./LTG_UI_view_item_sign_05";
import LTG_UI_view_item_sign_06 from "./LTG_UI_view_item_sign_06";
import LTG_UI_view_item_sign_07 from "./LTG_UI_view_item_sign_07";
import LTG_UI_btn_watchad01 from "./LTG_UI_btn_watchad01";
import LTG_UI_HideMenu from "./LTG_UI_HideMenu";
import LTG_UI_view_hidemenu from "./LTG_UI_view_hidemenu";
import LTG_UI_toggle_01 from "./LTG_UI_toggle_01";
import LTG_UI_view_set from "./LTG_UI_view_set";
import LTG_UI_RewardCode from "./LTG_UI_RewardCode";
import LTG_UI_view_rewardcode from "./LTG_UI_view_rewardcode";
import LTG_UI_TrySkin from "./LTG_UI_TrySkin";
import LTG_UI_view_tryskin from "./LTG_UI_view_tryskin";
import LTG_UI_VideoList from "./LTG_UI_VideoList";
import LTG_UI_top3 from "./LTG_UI_top3";
import LTG_UI_iconVdieo from "./LTG_UI_iconVdieo";
import LTG_UI_videoItem from "./LTG_UI_videoItem";
import LTG_UI_normal_btn from "./LTG_UI_normal_btn";
import LTG_UI_RanList from "./LTG_UI_RanList";
import LTG_UI_view_enter_code from "./LTG_UI_view_enter_code";
import LTG_UI_UnlockItem from "./LTG_UI_UnlockItem";
import LTG_UI_btn_unlock_ad from "./LTG_UI_btn_unlock_ad";
import LTG_UI_btn_refuse from "./LTG_UI_btn_refuse";
import LTG_UI_view_unlock from "./LTG_UI_view_unlock";
import LTG_UI_WatchGuide from "./LTG_UI_WatchGuide";
import LTG_UI_view_watchguide from "./LTG_UI_view_watchguide";
import LTG_UI_ScreenShoot from "./LTG_UI_ScreenShoot";
import LTG_UI_view_screenshoot from "./LTG_UI_view_screenshoot";

export default class LTComBinder{
	public static bindAll():void {
		fgui.UIObjectFactory.setExtension(LTG_UI_Set.URL, LTG_UI_Set);
		fgui.UIObjectFactory.setExtension(LTG_UI_Notice.URL, LTG_UI_Notice);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_notice.URL, LTG_UI_view_notice);
		fgui.UIObjectFactory.setExtension(LTG_UI_AddShortcut.URL, LTG_UI_AddShortcut);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_addshortcut.URL, LTG_UI_view_addshortcut);
		fgui.UIObjectFactory.setExtension(LTG_UI_FindGame.URL, LTG_UI_FindGame);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_findgame.URL, LTG_UI_view_findgame);
		fgui.UIObjectFactory.setExtension(LTG_UI_MyGame.URL, LTG_UI_MyGame);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_mygame.URL, LTG_UI_view_mygame);
		fgui.UIObjectFactory.setExtension(LTG_UI_Zhuawawa.URL, LTG_UI_Zhuawawa);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_zhuazi.URL, LTG_UI_view_zhuazi);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_zww.URL, LTG_UI_view_zww);
		fgui.UIObjectFactory.setExtension(LTG_UI_EggWall.URL, LTG_UI_EggWall);
		fgui.UIObjectFactory.setExtension(LTG_UI_btn_show_tips.URL, LTG_UI_btn_show_tips);
		fgui.UIObjectFactory.setExtension(LTG_UI_item_view_eggwall.URL, LTG_UI_item_view_eggwall);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_grow_01.URL, LTG_UI_view_grow_01);
		fgui.UIObjectFactory.setExtension(LTG_UI_Roll.URL, LTG_UI_Roll);
		fgui.UIObjectFactory.setExtension(LTG_UI_item_view_roll.URL, LTG_UI_item_view_roll);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_roll_panel.URL, LTG_UI_view_roll_panel);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_roll.URL, LTG_UI_view_roll);
		fgui.UIObjectFactory.setExtension(LTG_UI_WatchDY.URL, LTG_UI_WatchDY);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_watchdy.URL, LTG_UI_view_watchdy);
		fgui.UIObjectFactory.setExtension(LTG_UI_Sign.URL, LTG_UI_Sign);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_sign.URL, LTG_UI_view_sign);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_item_sign_01.URL, LTG_UI_view_item_sign_01);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_item_sign_02.URL, LTG_UI_view_item_sign_02);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_item_sign_03.URL, LTG_UI_view_item_sign_03);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_item_sign_05.URL, LTG_UI_view_item_sign_05);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_item_sign_06.URL, LTG_UI_view_item_sign_06);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_item_sign_07.URL, LTG_UI_view_item_sign_07);
		fgui.UIObjectFactory.setExtension(LTG_UI_btn_watchad01.URL, LTG_UI_btn_watchad01);
		fgui.UIObjectFactory.setExtension(LTG_UI_HideMenu.URL, LTG_UI_HideMenu);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_hidemenu.URL, LTG_UI_view_hidemenu);
		fgui.UIObjectFactory.setExtension(LTG_UI_toggle_01.URL, LTG_UI_toggle_01);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_set.URL, LTG_UI_view_set);
		fgui.UIObjectFactory.setExtension(LTG_UI_RewardCode.URL, LTG_UI_RewardCode);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_rewardcode.URL, LTG_UI_view_rewardcode);
		fgui.UIObjectFactory.setExtension(LTG_UI_TrySkin.URL, LTG_UI_TrySkin);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_tryskin.URL, LTG_UI_view_tryskin);
		fgui.UIObjectFactory.setExtension(LTG_UI_VideoList.URL, LTG_UI_VideoList);
		fgui.UIObjectFactory.setExtension(LTG_UI_top3.URL, LTG_UI_top3);
		fgui.UIObjectFactory.setExtension(LTG_UI_iconVdieo.URL, LTG_UI_iconVdieo);
		fgui.UIObjectFactory.setExtension(LTG_UI_videoItem.URL, LTG_UI_videoItem);
		fgui.UIObjectFactory.setExtension(LTG_UI_normal_btn.URL, LTG_UI_normal_btn);
		fgui.UIObjectFactory.setExtension(LTG_UI_RanList.URL, LTG_UI_RanList);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_enter_code.URL, LTG_UI_view_enter_code);
		fgui.UIObjectFactory.setExtension(LTG_UI_UnlockItem.URL, LTG_UI_UnlockItem);
		fgui.UIObjectFactory.setExtension(LTG_UI_btn_unlock_ad.URL, LTG_UI_btn_unlock_ad);
		fgui.UIObjectFactory.setExtension(LTG_UI_btn_refuse.URL, LTG_UI_btn_refuse);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_unlock.URL, LTG_UI_view_unlock);
		fgui.UIObjectFactory.setExtension(LTG_UI_WatchGuide.URL, LTG_UI_WatchGuide);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_watchguide.URL, LTG_UI_view_watchguide);
		fgui.UIObjectFactory.setExtension(LTG_UI_ScreenShoot.URL, LTG_UI_ScreenShoot);
		fgui.UIObjectFactory.setExtension(LTG_UI_view_screenshoot.URL, LTG_UI_view_screenshoot);
	}
}